pet_blog/blog/urls.py
from django.urls import path
from .views import PostListView, MyPostsView, PostDetailView, BlogsView, SubscriptionsView, FeedView

app_name = 'blog'
urlpatterns = [
    path('', PostListView.as_view(), name='posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('my-posts/', MyPostsView.as_view(), name='my-posts'),
    path('feed/', FeedView.as_view(), name='feed'),
    path('blogs/', BlogsView.as_view(), name='blogs'),
    path('subscriptions/', SubscriptionsView.as_view(), name='subscriptions')
]

pet_blog/pet_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

pet_blog/blog/models.py
import logging
from smtplib import SMTPException

from django.db import models
from django.core.mail import send_mail
from django.conf import settings

logger = logging.getLogger(__name__)


class Blog(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.author.get_username()


class Post(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    posted = models.DateTimeField(auto_now_add=True)
    content = models.TextField(max_length=10000)

    class Meta:
        ordering = ['-posted']

    def save(self, *args, **kwargs):
        super(Post, self).save(*args, **kwargs)
        subscriptions = Subscription.objects.filter(blog=self.blog)
        for subscription in subscriptions:
            subscriber = subscription.user
            feed = Feed(user=subscriber, post=self, subscription=subscription)
            feed.save()

            try:
                send_mail(
                    'New post',
                    'You have a new post in your feed.',
                    'from@pet-blog.com',
                    [subscriber.email],
                    fail_silently=False,
                )
            except SMTPException as e:
                logger.error(f"Unable to send email to {subscriber}: {e}")

    def __str__(self):
        return self.title


class Subscription(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['user', 'blog']

    def __str__(self):
        return self.blog.author.get_username()


class Feed(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    subscription = models.ForeignKey(Subscription, on_delete=models.CASCADE)
    is_read = models.BooleanField(default=False)

    class Meta:
        ordering = ['-post__posted']
        unique_together = ['user', 'post', 'subscription']

    def __str__(self):
        return self.post.title

pet_blog/blog/forms.py
from django import forms

from .models import Post, Blog
from .widgets import FeedWidget


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content')
        labels = {
            'title': '',
            'content': '',
        }
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Title...'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Text...'}),
        }


class SubscriptionForm(forms.Form):
    def __init__(self, user, *args, **kwargs):
        super(SubscriptionForm, self).__init__(*args, **kwargs)
        self.fields['blogs'].queryset = Blog.objects.exclude(author=user).exclude(
            author__in=user.subscription_set.all().values('blog__author'))

    blogs = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(attrs={'class': 'form-check-input'}),
        queryset=None
    )


class UnSubscriptionForm(forms.Form):
    def __init__(self, user, *args, **kwargs):
        super(UnSubscriptionForm, self).__init__(*args, **kwargs)
        self.fields['subscriptions'].queryset = user.subscription_set.all()

    subscriptions = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(attrs={'class': 'form-check-input'}),
        queryset=None
    )


class FeedForm(forms.Form):
    def __init__(self, user, *args, **kwargs):
        super(FeedForm, self).__init__(*args, **kwargs)
        self.fields['feeds'].queryset = user.feed_set.filter(is_read=False)

    feeds = forms.ModelMultipleChoiceField(
        widget=FeedWidget(attrs={'class': 'form-check-input'}),
        queryset=None
    )

pet_blog/blog/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, CreateView, FormView
from django.urls import reverse_lazy
from django.db import transaction

from .forms import PostForm, SubscriptionForm, UnSubscriptionForm, FeedForm
from .models import Blog, Post, Feed, Subscription


class PostListView(ListView):
    model = Post
    template_name = 'blog/posts.html'
    context_object_name = 'posts'


class PostDetailView(DetailView):
    model = Post
    context_object_name = 'post'


@method_decorator(login_required(login_url=reverse_lazy('admin:index')), name='dispatch')
class MyPostsView(CreateView):
    model = Post
    template_name = 'blog/my_posts.html'
    form_class = PostForm
    success_url = reverse_lazy('blog:my-posts')

    def get_context_data(self, **kwargs):
        user = self.request.user
        kwargs['posts'] = Post.objects.filter(blog__author=user)
        return super(MyPostsView, self).get_context_data(**kwargs)

    def form_valid(self, form):
        form.instance.blog = Blog.objects.get(author=self.request.user)
        return super().form_valid(form)


@method_decorator(login_required(login_url=reverse_lazy('admin:index')), name='dispatch')
class FeedView(FormView):
    template_name = 'blog/feed.html'
    form_class = FeedForm
    success_url = reverse_lazy('blog:feed')

    def get_form(self):
        form_class = self.get_form_class()
        return form_class(self.request.user, **self.get_form_kwargs())

    def form_valid(self, form):
        feeds = form.cleaned_data['feeds']
        for feed in feeds:
            feed.is_read = True
        Feed.objects.bulk_update(feeds, ['is_read'])
        return super().form_valid(form)


@method_decorator(login_required(login_url=reverse_lazy('admin:index')), name='dispatch')
class BlogsView(FormView):
    template_name = 'blog/blogs.html'
    form_class = SubscriptionForm
    success_url = reverse_lazy('blog:blogs')

    def get_form(self):
        form_class = self.get_form_class()
        return form_class(self.request.user, **self.get_form_kwargs())

    @transaction.atomic
    def form_valid(self, form):
        user = self.request.user
        blogs = form.cleaned_data['blogs']

        for blog in blogs:
            subscription = Subscription(user=user, blog=blog)
            subscription.save()

            posts = Post.objects.filter(blog=blog)
            Feed.objects.bulk_create(
                [Feed(user=user, post=post, subscription=subscription) for post in posts])
        return super().form_valid(form)


@method_decorator(login_required(login_url=reverse_lazy('admin:index')), name='dispatch')
class SubscriptionsView(FormView):
    template_name = 'blog/subscriptions.html'
    form_class = UnSubscriptionForm
    success_url = reverse_lazy('blog:subscriptions')

    def get_form(self):
        form_class = self.get_form_class()
        return form_class(self.request.user, **self.get_form_kwargs())

    def form_valid(self, form):
        subscriptions = form.cleaned_data['subscriptions']
        subscriptions.delete()
        return super().form_valid(form)

pet_blog/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pet-Blog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:feed' %}">Feed</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:blogs' %}">Blogs</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:subscriptions' %}">Subscriptions</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:my-posts' %}">My Posts</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:logout' %}">Log Out ({{ user.get_username }})</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">Log In</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="container-lg my-3">
    {% block content %}
    {% endblock content %}
</div>
</body>
</html>

pet_blog/blog/templates/blog/blogs.html
{% extends 'blog/base.html' %}

{% block content %}
<h1>Blogs</h1>
{% if form.blogs|length %}
<form method="post">
    {% csrf_token %}
    {% include 'blog/includes/subscription_field_set.html' with choices=form.blogs %}
    <button type="submit" class="btn btn-outline-danger btn-sm">Subscribe</button>
</form>
{% else %}
<p>No blogs found</p>
{% endif %}
{% endblock content %}

pet_blog/blog/templates/blog/feed.html
{% extends 'blog/base.html' %}

{% block content %}
<h1>Feed</h1>
{% if form.feeds|length %}
<form method="post">
    {% csrf_token %}
    {% for checkbox in form.feeds %}
    <div class="form-check mb-3">
        {{ checkbox }}
    </div>
    {% endfor %}
    <button type="submit" class="btn btn-outline-secondary btn-sm">Is Read</button>
</form>
{% else %}
<p>No posts found</p>
{% endif %}
{% endblock content %}

pet_blog/blog/templates/blog/includes/posts_list.html
<div class="list-group">
    {% for post in posts %}
    <a href="{% url 'blog:post-detail' post.pk %}" class="list-group-item list-group-item-action">{{post.title}} <div class="text-muted">posted {{ post.posted|date:"M d, Y h:m" }}</div></a>
    {% endfor %}
</div>

pet_blog/blog/templates/blog/includes/subscription_field_set.html
<fieldset class="mb-3">
    {% for checkbox in choices %}
    <div class="form-check">
        {{ checkbox.tag }}
        <label class="form-check-label" for="{{ checkbox.id_for_label }}">
            {{ checkbox.choice_label }}
        </label>
    </div>
    {% endfor %}
</fieldset>

pet_blog/blog/templates/blog/my_posts.html
{% extends 'blog/base.html' %}

{% block content %}
<h1>My posts</h1>
<form method="POST" class="post-form mb-3">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-outline-danger">Post</button>
</form>
{% if posts %}
{% include 'blog/includes/posts_list.html' with posts=posts %}
{% endif %}
{% endblock content %}

pet_blog/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
<h1>{{ post.title }}</h1>

<div class="card mb-2">
    <div class="card-body">
        <h6 class="card-subtitle mb-2 text-muted">posted {{ post.posted|date:"M d, Y h:m" }}</h6>
        <p class="card-text">{{ post.content }}</p>
    </div>
</div>
{% endblock content %}

pet_blog/blog/templates/blog/posts.html
{% extends 'blog/base.html' %}

{% block content %}
<h1>Posts</h1>
{% if posts %}
{% include 'blog/includes/posts_list.html' with posts=posts %}
{% else %}
<p>No posts found</p>
{% endif %}
{% endblock content %}

pet_blog/blog/templates/blog/subscriptions.html
{% extends 'blog/base.html' %}

{% block content %}
<h1>Subscriptions</h1>
{% if form.subscriptions|length %}
<form method="post">
    {% csrf_token %}
    {% include 'blog/includes/subscription_field_set.html' with choices=form.subscriptions %}
    <button type="submit" class="btn btn-outline-secondary btn-sm">Unsubscribe</button>
</form>
{% else %}
<p>No subscriptions found</p>
{% endif %}
{% endblock content %}

pet_blog/blog/templates/blog/widgets/feed_option.html
{% include "django/forms/widgets/input.html" %} <label class="form-check-label" for="{{ widget.attrs.id }}"><a href="{% url 'blog:post-detail' widget.value.instance.post.pk %}">{{ widget.value.instance.post }}</a></label>